services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: repowatch-frontend

    ports:
      - "3000:80"

    networks:
      - repowatch-net

    restart: unless-stopped

networks:
  repowatch-net:
    external: true
